version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: algorank-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: algorank
      POSTGRES_PASSWORD: algorank
      POSTGRES_DB: algorank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
